version: "3.9"
services:
  api:
    build: steamfriendsgamesapi/.
    ports:
      - "5000:5000"
    network_mode: host
  discord-bot:
    build: steamfriendsgamesdiscordbot/.
    network_mode: host
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"